apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backup-state-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClass: local-path # 기존 postgres-cluster.yaml에서 사용 중인 클래스
